"use client";

import { useEffect, useMemo, useState } from "react";

type User={id:string;email:string;full_name:string;role:string;plan_slug?:string;suspended:boolean;created_at:string;protected:boolean};
type Overview={profiles:any[];classes:any[];rooms:any[];teacherProfiles:any[];assignments:any[];materials:any[];schedules:any[];attendance:any[]};
type Tab="overview"|"users"|"teachers"|"data";

const roleLabel=(r:string)=>r==='teacher'?'Giáo viên':r==='admin'?'Quản trị viên':'Học sinh';

export default function AdminCenter(){
 const [users,setUsers]=useState<User[]>([]),[stats,setStats]=useState<any>(null),[overview,setOverview]=useState<Overview|null>(null);
 const [q,setQ]=useState(''),[tab,setTab]=useState<Tab>('overview'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState(''),[saving,setSaving]=useState('');
 async function load(){setLoading(true);setError('');try{const [u,s,o]=await Promise.all([fetch('/api/admin/users',{cache:'no-store'}),fetch('/api/admin/stats',{cache:'no-store'}),fetch('/api/admin/overview',{cache:'no-store'})]);const [uj,sj,oj]=await Promise.all([u.json(),s.json(),o.json()]);if(!u.ok)throw new Error(uj.error||'Không tải được tài khoản.');if(!s.ok)throw new Error(sj.error||'Không tải được thống kê.');if(!o.ok)throw new Error(oj.error||'Không tải được dữ liệu hệ thống.');setUsers(Array.isArray(uj)?uj:[]);setStats(sj);setOverview(oj);}catch(e){setError(e instanceof Error?e.message:'Không tải được dữ liệu Admin.');}finally{setLoading(false);}}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>{const x=q.trim().toLowerCase();return !x?users:users.filter(u=>`${u.email} ${u.full_name} ${u.role}`.toLowerCase().includes(x));},[users,q]);
 async function mutateUser(userId:string,action:string){setSaving(userId+action);setError('');setSuccess('');try{const r=await fetch('/api/admin/users',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({userId,action})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Cập nhật thất bại.');setSuccess(d.message||'Đã cập nhật tài khoản.');await load();}catch(e){setError(e instanceof Error?e.message:'Cập nhật thất bại.');}finally{setSaving('');}}
 async function removeUser(userId:string,email:string){if(!confirm(`Xóa tài khoản ${email}? Thao tác này không thể hoàn tác.`))return;setSaving(userId+'delete');try{const r=await fetch('/api/admin/users',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({userId})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Xóa thất bại.');setSuccess('Đã xóa tài khoản.');await load();}catch(e){setError(e instanceof Error?e.message:'Xóa thất bại.');}finally{setSaving('');}}
 if(loading)return <main className="grid min-h-screen place-items-center bg-[#070b14] text-white"><div className="text-center"><div className="mx-auto h-10 w-10 animate-spin rounded-full border-4 border-white/10 border-t-indigo-400"/><p className="mt-4 font-semibold text-slate-300">Đang tải Admin Center…</p></div></main>;
 const statsCards=[['👥','Tài khoản',stats?.total_users],['👨‍🏫','Giáo viên',stats?.teachers],['👨‍🎓','Học sinh',stats?.students],['🏫','Lớp học',overview?.classes?.length],['🎥','Phòng học',overview?.rooms?.length]];
 return <main className="min-h-screen bg-[#070b14] text-white">
  <header className="sticky top-0 z-40 border-b border-white/10 bg-[#070b14]/90 px-4 py-4 backdrop-blur-xl sm:px-6"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-[.32em] text-indigo-300">STUDY26 CONTROL</div><h1 className="mt-1 text-2xl font-black tracking-tight sm:text-3xl">Admin Center</h1></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border border-white/10 px-3 py-2 text-sm font-black hover:bg-white/10">↻</button><a href="/dashboard" className="rounded-xl bg-white px-4 py-2 text-sm font-black text-slate-900">Dashboard</a></div></div></header>
  <div className="mx-auto max-w-7xl p-4 sm:p-6">
   {error&&<div className="mb-4 rounded-2xl border border-red-400/20 bg-red-500/10 p-4 text-sm font-semibold text-red-200">⚠️ {error}</div>}{success&&<div className="mb-4 rounded-2xl border border-emerald-400/20 bg-emerald-500/10 p-4 text-sm font-semibold text-emerald-200">✅ {success}</div>}
   <div className="mb-6 flex gap-2 overflow-x-auto">{([['overview','Tổng quan','◈'],['users','Tài khoản','👤'],['teachers','Giáo viên','👨‍🏫'],['data','Dữ liệu hệ thống','▦']] as const).map(([key,label,icon])=><button key={key} onClick={()=>setTab(key)} className={`shrink-0 rounded-xl px-4 py-2.5 text-sm font-black ${tab===key?'bg-indigo-500 shadow-lg shadow-indigo-500/20':'border border-white/10 bg-white/[.03] text-slate-400 hover:bg-white/[.08]'}`}>{icon} {label}</button>)}</div>
   {tab==='overview'&&<div className="space-y-6"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{statsCards.map(([i,l,v])=><div key={String(l)} className="rounded-3xl border border-white/10 bg-white/[.04] p-5 shadow-xl shadow-black/10"><div className="text-2xl">{i}</div><div className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-500">{l}</div><div className="mt-1 text-3xl font-black">{Number(v||0).toLocaleString('vi-VN')}</div></div>)}</section><section className="grid gap-5 lg:grid-cols-2"><DataTable title="Phòng học gần đây" rows={overview?.rooms||[]} compact/><DataTable title="Lớp học gần đây" rows={overview?.classes||[]} compact/></section></div>}
   {tab==='users'&&<section className="rounded-3xl border border-white/10 bg-white/[.04] p-4 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-2xl font-black">Quản lý tài khoản</h2><p className="mt-1 text-sm text-slate-400">Đổi vai trò, khóa/mở khóa hoặc xóa tài khoản.</p></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm tên, email, vai trò…" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-indigo-400 lg:w-96"/></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="border-b border-white/10 text-left text-xs uppercase tracking-wider text-slate-500"><tr><th className="pb-4">Tài khoản</th><th className="pb-4">Vai trò</th><th className="pb-4">Trạng thái</th><th className="pb-4 text-right">Thao tác</th></tr></thead><tbody className="divide-y divide-white/10">{filtered.map(u=>{const busy=saving.startsWith(u.id);return <tr key={u.id}><td className="py-4"><div className="font-bold">{u.full_name||'Chưa đặt tên'}</div><div className="mt-1 text-xs text-slate-500">{u.email}</div></td><td>{u.protected?<span className="rounded-full bg-indigo-400/10 px-2.5 py-1 text-xs font-black text-indigo-300">ADMIN CHÍNH</span>:<span className="rounded-full bg-white/[.05] px-2.5 py-1 text-xs font-bold">{roleLabel(u.role)}</span>}</td><td>{u.suspended?<span className="text-red-300">🔒 Đang khóa</span>:<span className="text-emerald-300">✅ Hoạt động</span>}</td><td className="text-right">{!u.protected&&<div className="flex justify-end gap-2"><button disabled={busy} onClick={()=>mutateUser(u.id,u.role==='teacher'?'demote_user':'promote_teacher')} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-black disabled:opacity-40">{u.role==='teacher'?'Hạ GV':'Lên GV'}</button><button disabled={busy} onClick={()=>mutateUser(u.id,'toggle_suspended')} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-black disabled:opacity-40">{u.suspended?'Mở khóa':'Khóa'}</button><button disabled={busy} onClick={()=>removeUser(u.id,u.email)} className="rounded-lg bg-red-500/10 px-3 py-2 text-xs font-black text-red-300 disabled:opacity-40">Xóa</button></div>}</td></tr>})}</tbody></table></div></section>}
   {tab==='teachers'&&<section className="space-y-4">{(overview?.teacherProfiles||[]).map((t:any)=>{const p=overview?.profiles?.find((x:any)=>x.id===t.user_id);return <article key={t.user_id} className="rounded-3xl border border-white/10 bg-white/[.04] p-5 sm:p-6"><div className="flex flex-col gap-5 sm:flex-row"><div className="h-24 w-24 shrink-0 overflow-hidden rounded-3xl bg-white/10">{p?.avatar_url?<img src={p.avatar_url} alt="" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-4xl">👨‍🏫</div>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-xl font-black">{p?.full_name||'Giáo viên'}</h3>{t.verified&&<span className="rounded-full bg-emerald-400/10 px-2.5 py-1 text-xs font-black text-emerald-300">✓ Đã xác minh</span>}</div><p className="mt-1 text-indigo-300">{t.headline||'Chưa cập nhật chức danh'}</p><div className="mt-4 grid gap-3 text-sm text-slate-300 sm:grid-cols-2 lg:grid-cols-4"><div>🎓 {t.education||'—'}</div><div>📚 {t.specialization||'—'}</div><div>⏳ {t.experience_years||0} năm</div><div>👨‍🎓 {t.students_taught||0} học sinh</div></div><div className="mt-4 space-y-2 text-sm text-slate-400"><div>🏫 {t.schools||'Chưa cập nhật'}</div><div>🏆 {t.achievements||'Chưa cập nhật'}</div></div></div></div></article>})}{(!overview?.teacherProfiles||overview.teacherProfiles.length===0)&&<Empty text="Chưa có hồ sơ giáo viên."/>}</section>}
   {tab==='data'&&<section className="space-y-5"><DataTable title="Lớp học" rows={overview?.classes||[]}/><DataTable title="Phòng học" rows={overview?.rooms||[]}/><DataTable title="Bài tập" rows={overview?.assignments||[]}/><DataTable title="Tài liệu" rows={overview?.materials||[]}/><DataTable title="Lịch" rows={overview?.schedules||[]}/><DataTable title="Điểm danh" rows={overview?.attendance||[]}/></section>}
  </div>
 </main>
}
function Empty({text}:{text:string}){return <div className="rounded-3xl border border-dashed border-white/10 p-10 text-center text-slate-500">{text}</div>}
function DataTable({title,rows,compact=false}:{title:string;rows:any[];compact?:boolean}){const visible=rows.slice(0,compact?8:30);return <section className="rounded-3xl border border-white/10 bg-white/[.04] p-5 sm:p-6"><div className="flex items-end justify-between gap-3"><div><h2 className="text-xl font-black">{title}</h2><p className="mt-1 text-xs text-slate-500">{rows.length} bản ghi</p></div></div>{visible.length===0?<Empty text="Chưa có dữ liệu."/>:<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[600px] text-sm"><thead className="border-b border-white/10 text-left text-xs uppercase text-slate-500"><tr><th className="pb-3">ID</th><th className="pb-3">Tên</th><th className="pb-3">Liên quan</th><th className="pb-3">Thời gian</th></tr></thead><tbody className="divide-y divide-white/10">{visible.map((r:any,i:number)=><tr key={r.id||i}><td className="py-3 font-mono text-xs text-slate-500">{String(r.id||'—').slice(0,14)}</td><td className="py-3 font-semibold">{r.name||r.title||r.full_name||'—'}</td><td className="py-3 text-slate-400">{r.code||r.class_id||r.teacher_id||r.created_by||'—'}</td><td className="py-3 text-xs text-slate-500">{r.created_at?new Date(r.created_at).toLocaleString('vi-VN'):r.starts_at?new Date(r.starts_at).toLocaleString('vi-VN'):'—'}</td></tr>)}</tbody></table></div>}</section>}
