'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';

type Klass={id:string;name:string;description:string|null;code:string;teacher_id:string};
export default function ClassManager({classes,isTeacher}:{classes:Klass[];isTeacher:boolean}){
 const router=useRouter(); const [items,setItems]=useState(classes); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [editing,setEditing]=useState<string|null>(null); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);
 async function save(){if(!name.trim())return;setBusy(true);setMsg('');const r=await fetch('/api/classes',{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:editing,name,description})});const d=await r.json();if(!r.ok){setMsg(d.error||'Không thể lưu lớp.');setBusy(false);return;}setItems(v=>editing?v.map(x=>x.id===d.id?d:x):[d,...v]);setName('');setDescription('');setEditing(null);setMsg(editing?'Đã cập nhật lớp.':'Đã tạo lớp.');router.refresh();setBusy(false);}
 function edit(c:Klass){setEditing(c.id);setName(c.name);setDescription(c.description||'');window.scrollTo({top:0,behavior:'smooth'});}
 return <section className="mt-6 rounded-3xl border bg-white p-6 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-black">🏫 Lớp học</h2><p className="text-sm text-slate-500">Tạo, sửa và quản lý các lớp của bạn.</p></div>{isTeacher&&<div className="text-sm font-bold text-slate-500">{items.length} lớp</div>}</div>{isTeacher&&<div className="mt-5 grid gap-3 md:grid-cols-[1fr_1fr_auto_auto]"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Tên lớp" className="rounded-xl border p-3"/><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Mô tả" className="rounded-xl border p-3"/><button disabled={busy||!name.trim()} onClick={save} className="rounded-xl bg-indigo-600 px-5 py-3 font-black text-white disabled:opacity-40">{editing?'Lưu thay đổi':'Tạo lớp'}</button>{editing&&<button onClick={()=>{setEditing(null);setName('');setDescription('')}} className="rounded-xl border px-5 py-3 font-bold">Hủy</button>}</div>}{msg&&<p className="mt-3 text-sm text-slate-500">{msg}</p>}<div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{items.map(c=><article key={c.id} className="rounded-2xl border p-4"><div className="font-black">{c.name}</div><div className="mt-1 text-sm text-slate-500">Mã lớp: <b>{c.code}</b></div>{c.description&&<p className="mt-2 text-sm text-slate-500">{c.description}</p>}{isTeacher&&<button onClick={()=>edit(c)} className="mt-4 rounded-lg border px-3 py-2 text-sm font-bold">✏️ Sửa lớp</button>}</article>)}{items.length===0&&<p className="text-sm text-slate-400">Chưa có lớp.</p>}</div></section>
}
