'use client';
import { useEffect, useState } from 'react';
import { RoomEvent, RemoteParticipant, Participant } from 'livekit-client';
import { useParticipants, useRoomContext } from '@livekit/components-react';

export default function LiveFeatureBar({role,features,roomId,roomName,roomTitle,onLeave}:{role:string;features:Record<string,boolean>;roomId:string;roomName:string;roomTitle:string;onLeave:()=>void}){
 const room=useRoomContext();const participants=useParticipants();const[panel,setPanel]=useState<'chat'|'people'|null>(null);const[message,setMessage]=useState('');const[chat,setChat]=useState<{id:string;name:string;text:string;mine?:boolean}[]>([]);const[raised,setRaised]=useState(false);const[recording,setRecording]=useState(false);const[egressId,setEgressId]=useState('');const[notice,setNotice]=useState('');
 useEffect(()=>{const fn=(payload:Uint8Array,p?:RemoteParticipant|Participant)=>{try{const d=JSON.parse(new TextDecoder().decode(payload));if(d?.type==='study26-chat')setChat(v=>[...v,{id:crypto.randomUUID(),name:p?.name||p?.identity||'Người dùng',text:String(d.text||'')}]);if(d?.type==='study26-hand'&&p?.identity) setNotice(d.raised?`${p.name||p.identity} đã giơ tay.`:'');}catch{}};room.on(RoomEvent.DataReceived,fn);return()=>{room.off(RoomEvent.DataReceived,fn)}},[room]);
 async function sendChat(){const text=message.trim();if(!text||!features.chat)return;await room.localParticipant.publishData(new TextEncoder().encode(JSON.stringify({type:'study26-chat',text})),{reliable:true});setChat(v=>[...v,{id:crypto.randomUUID(),name:room.localParticipant.name||room.localParticipant.identity,text,mine:true}]);setMessage('')}
 async function hand(){if(!features.hand_raise)return;const next=!raised;setRaised(next);await room.localParticipant.publishData(new TextEncoder().encode(JSON.stringify({type:'study26-hand',raised:next})),{reliable:true});}
 async function kick(identity:string){setNotice('Đang kick…');const r=await fetch('/api/live/kick',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({roomId,identity})});const d=await r.json();setNotice(r.ok?'Đã kick người dùng.':d.error||'Không thể kick.');}
 async function record(){if(!features.recording||role!=='teacher')return;setNotice('Đang xử lý ghi hình…');const r=await fetch('/api/recording',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({roomName,action:recording?'stop':'start',egressId})});const d=await r.json();if(!r.ok){setNotice(d.error||'Không thể ghi hình.');return;}setRecording(!recording);setEgressId(recording?'':String(d.egressId||''));setNotice(recording?'Đã dừng ghi hình.':'Đang ghi hình phòng học.');}
 function leave(){room.disconnect().finally(onLeave)}
 return <><div className="fixed inset-x-0 bottom-0 z-50 px-2 pb-[max(8px,env(safe-area-inset-bottom))] sm:px-4"><div className="mx-auto max-w-5xl rounded-2xl border border-white/10 bg-slate-950/95 p-2 shadow-2xl backdrop-blur-xl"><div className="flex items-center gap-1.5 overflow-x-auto"><div className="hidden min-w-0 flex-1 px-2 sm:block"><div className="truncate text-xs font-black uppercase tracking-wide text-indigo-300">Study26</div><div className="truncate text-sm font-bold">{roomTitle}</div></div>{features.chat&&<button onClick={()=>setPanel(panel==='chat'?null:'chat')} className="shrink-0 rounded-xl bg-white/5 px-3 py-3 text-xs font-black hover:bg-white/10">💬 <span className="hidden sm:inline">Chat</span></button>}{features.hand_raise&&<button onClick={hand} className={`shrink-0 rounded-xl px-3 py-3 text-xs font-black ${raised?'bg-amber-400 text-slate-950':'bg-white/5 hover:bg-white/10'}`}>✋</button>}{features.kick&&(role==='teacher'||role==='admin')&&<button onClick={()=>setPanel(panel==='people'?null:'people')} className="shrink-0 rounded-xl bg-white/5 px-3 py-3 text-xs font-black hover:bg-white/10">👥</button>}{features.recording&&(role==='teacher'||role==='admin')&&<button onClick={record} className={`shrink-0 rounded-xl px-3 py-3 text-xs font-black ${recording?'bg-red-500':'bg-white/5 hover:bg-white/10'}`}>{recording?'⏹':'⏺'}</button>}<div className="shrink-0 rounded-xl bg-white/5 px-3 py-3 text-xs font-black text-slate-300">👥 {participants.length}</div><button onClick={leave} className="shrink-0 rounded-xl bg-red-500 px-3 py-3 text-xs font-black hover:bg-red-400">🚪 <span className="hidden sm:inline">Rời phòng</span></button></div></div></div>
 {panel==='chat'&&features.chat&&<aside className="fixed inset-x-2 bottom-[78px] z-40 flex h-[min(62dvh,500px)] flex-col overflow-hidden rounded-3xl border bg-white text-slate-900 shadow-2xl sm:inset-x-auto sm:bottom-24 sm:right-5 sm:h-[500px] sm:w-[360px]"><div className="flex items-center justify-between bg-slate-950 px-4 py-4 text-white"><b>💬 Chat lớp</b><button onClick={()=>setPanel(null)} className="text-xl">×</button></div><div className="flex-1 space-y-2 overflow-y-auto bg-slate-50 p-3">{chat.map(c=><div key={c.id} className={`flex ${c.mine?'justify-end':'justify-start'}`}><div className={`max-w-[85%] rounded-2xl px-3 py-2 text-sm ${c.mine?'bg-indigo-600 text-white':'border bg-white'}`}><div className="mb-1 text-[10px] font-bold opacity-60">{c.name}</div>{c.text}</div></div>)}{chat.length===0&&<div className="py-10 text-center text-sm text-slate-400">Chưa có tin nhắn.</div>}</div><div className="border-t p-3"><div className="flex gap-2"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendChat()} className="min-w-0 flex-1 rounded-xl border p-2.5" placeholder="Nhập tin nhắn…"/><button onClick={sendChat} className="rounded-xl bg-indigo-600 px-4 font-black text-white">Gửi</button></div></div></aside>}
 {panel==='people'&&features.kick&&(role==='teacher'||role==='admin')&&<aside className="fixed inset-x-2 bottom-[78px] z-40 max-h-[55dvh] overflow-y-auto rounded-3xl border bg-white p-4 text-slate-900 shadow-2xl sm:inset-x-auto sm:bottom-24 sm:right-5 sm:w-80"><div className="mb-3 flex items-center justify-between"><b>👥 Người tham gia</b><button onClick={()=>setPanel(null)} className="text-xl">×</button></div>{participants.filter(p=>p.identity!==room.localParticipant.identity).map(p=><div key={p.identity} className="flex items-center justify-between gap-2 border-b py-3 last:border-0"><span className="truncate text-sm font-bold">{p.name||p.identity}</span><button onClick={()=>kick(p.identity)} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-black text-red-600">Kick</button></div>)}</aside>}
 {notice&&<div className="fixed bottom-20 left-1/2 z-[60] -translate-x-1/2 rounded-xl bg-white px-4 py-2 text-xs font-black text-slate-900 shadow-xl">{notice}</div>}</>
}
